AWSTemplateFormatVersion: '2010-09-09-OC'
Description: default template generated for organization with master account 897722709367

Organization:
  ManagementAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      AccountName: ganbatte
      AccountId: '897722709367'
      RootEmail: {{ secrets.ROOT_EMAIL}}

  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:
      DefaultOrganizationAccessRoleName: OrganizationAccountAccessRole


