AWSTemplateFormatVersion: '2010-09-09-OC'
Description: default template generated for organization with master account 897722709367

Organization:
  ManagementAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      AccountName: ganbatte
      AccountId: '897722709367'
      RootEmail: {{ secrets.ROOT_EMAIL}}

  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:
      DefaultOrganizationAccessRoleName: OrganizationAccountAccessRole

  ProductionOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: production
      Accounts: 
        - Ref: ProductionAccount1

  TestOU:
     Type: OC::ORG::OrganizationalUnit
     Properties:
      OrganizationalUnitName: test
      Accounts: 
        - Ref: TestAccount1

  TestAccount1:
    Type: OC::ORG::Account
    Properties:
      Alias: test-account-1-5577CC
      AccountName: Test Account 1
      RootEmail: riyoko.kimura+test1@proton.me
  
  ProductionAccount1:
    Type: OC::ORG::Account
    Properties:
      Alias: prod-account-1-5577CC
      AccountName: Production Account 1
      RootEmail: ${{ secrets.PROD_EMAIL_ACCOUNT01 }}